<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once dirname(__DIR__) . '/includes/automations/facebook-automations.php';
require_once dirname(__DIR__) . '/includes/resort/stay-photos.php';
function checkFacebook(bool $condition, string $message): void {
    if (!$condition) throw new RuntimeException($message);
}
try {
    checkFacebook(facebookCategory('Magkano po ang room?') === 'rates', 'Filipino rates classification');
    checkFacebook(facebookCategory('Pwede po ba magpareserve?', true, facebookDefaultRules()['keywords']) === 'booking', 'Editable Tagalog booking classification');
    checkFacebook(facebookCategory('Malapit ba kayo sa bayan?', true, facebookDefaultRules()['keywords']) === 'location', 'Editable Tagalog location classification');
    checkFacebook(facebookCategory('This is a separate question') === 'general', 'Keyword boundaries avoid partial-word matches');
    checkFacebook(facebookCategory('Is a room avalable next weekend?') === 'booking', 'Conservative booking typo matching');
    checkFacebook(facebookCategory('What amnities do you have?') === 'amenities', 'Conservative amenity typo matching');
    checkFacebook(facebookCategory('Please send your locaton') === 'location', 'Conservative location typo matching');
    checkFacebook(facebookCategory('Next weekend for 5 guests') === 'booking', 'Dates plus party size imply booking intent');
    checkFacebook(facebookCategory('Guests: 5') === 'booking', 'Label-first guest count starts booking flow');
    checkFacebook(facebookCategory('5 guests') === 'booking', 'Number-first guest count starts booking flow');
    checkFacebook(facebookCategory("I'd like to inqure") === 'booking', 'Common inquiry misspelling starts booking flow');
    checkFacebook(facebookConversationDetails("I'd like to inqure")['guest_name'] === '', 'Inquiry wording is not mistaken for a guest name');
    checkFacebook(facebookCategory("I'd like to inquire about rates") === 'rates', 'A specific inquiry keeps its matching information category');
    checkFacebook(facebookCategory('hm') === 'rates', 'Price shorthand starts the rate flow');
    checkFacebook(facebookConversationDetails('hm')['guest_name'] === '', 'Price shorthand is not mistaken for a guest name');
    checkFacebook(facebookCategory('how much po') === 'rates', 'English price question starts the rate flow');
    checkFacebook(facebookCategory('magkano po') === 'rates', 'Tagalog price question starts the rate flow');
    checkFacebook(facebookCategory("Dates: October 10 to October 12, 2027\nGuests: 5\nMagkano po?") === 'rates', 'Rate intent stays authoritative when dates and pax are included');
    checkFacebook(facebookCategory('11am checkin') === 'booking', 'Explicit check-in time starts booking flow');
    checkFacebook(facebookCategory("Dates: October 10 to October 12, 2027\nGuests: 5\nActivities: ATV rental") === 'booking', 'Structured booking details take priority over activities keyword');
    checkFacebook(facebookCategory('inquire p ako for sep 15-19') === 'booking', 'Short casual inquiry with dates implies booking intent');
    checkFacebook(facebookConversationGuests("Dates: October 10 to October 12, 2027\nGuests: 5\n11am checkin", true) === 5, 'Date year cannot leak into the following guest count');
    checkFacebook(str_contains(facebookDefaultRules()['templates']['location'], 'google.com/maps/'), 'Location reply includes Google Maps');
    checkFacebook(str_contains(facebookDefaultRules()['templates']['rates'], 'Leave this blank if you want us to suggest the best fit') && str_contains(facebookDefaultRules()['templates']['rates'], 'Requested activities (optional) — ATV, banana boat, or jet ski rental'), 'Rates template explains optional accommodation and activities without repetition');
    checkFacebook(facebookCategory('Booking complaint: refund please') === 'complaint', 'Complaint priority');
    checkFacebook(facebookCategory('Is there availability?', false) === 'general', 'Disabled classification');
    checkFacebook(facebookProfileName(['name' => '  Maria   Santos  ']) === 'Maria Santos', 'Messenger profile name normalization');
    checkFacebook(facebookProfileName(['name' => '']) === null, 'Empty Messenger profile name fallback');
    checkFacebook(str_starts_with(facebookStaffTakeoverNotice(), 'You are now chatting with a staff member.'), 'Staff takeover notice is available as a separate message');
    checkFacebook(facebookWebhookMessageBody(['text' => 'Hello 😊'])['body'] === 'Hello 😊', 'Unicode emoji text is preserved');
    checkFacebook(facebookWebhookMessageBody(['sticker_id' => 1])['body'] === '👍', 'Messenger quick-like sticker is displayed without triggering a reply');
    $photoMessage = facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'https://scontent.example.test/photo.jpg']]]]);
    checkFacebook($photoMessage['body'] === '📷 Photo received' && $photoMessage['attachment_type'] === 'image' && $photoMessage['attachment_url'] === 'https://scontent.example.test/photo.jpg' && !$photoMessage['automatic_reply'], 'Incoming photo URL is retained without triggering a reply');
    $stickerMessage = facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'https://scontent.xx.fbcdn.net/v/t39.1997-6/thumb.png']]]]);
    checkFacebook($stickerMessage['body'] === '👍' && $stickerMessage['attachment_type'] === 'sticker', 'Messenger sticker image is identified for compact display');
    checkFacebook(facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'javascript:alert(1)']]]])['attachment_url'] === null, 'Unsafe attachment URL is rejected');
    $customRules = facebookDefaultRules();
    $customRules['guided_replies']['ask_guests'] = 'CUSTOM GUEST QUESTION';
    checkFacebook(facebookConversationPrompt('awaiting_guests', $customRules) === 'CUSTOM GUEST QUESTION', 'Guided reply customization');
    checkFacebook(str_contains(facebookGuidedReply($customRules, 'pending_created', ['reference' => 'OD-TEST']), 'OD-TEST'), 'Guided placeholder replacement');
    checkFacebook(facebookConversationDates('next weekend') !== null, 'Natural next-weekend dates');
    checkFacebook(facebookConversationDates('October 10 to 12') !== null, 'Natural month-name dates');
    checkFacebook(facebookConversationDates('next wekend') !== null, 'Misspelled relative dates');
    checkFacebook(facebookConversationDates('Octber 10') !== null, 'Misspelled single-date stay');
    checkFacebook(facebookConversationGuests('2 adults and 3 kids') === 5, 'Combined adult and child count');
    checkFacebook(facebookConversationGuests('lima kami') === 5, 'Written Tagalog guest count');
    checkFacebook(facebookConversationGuests('fiev people') === 5, 'Conservative written-number typo');
    checkFacebook(facebookConversationGuests('October 10 to 12 for 5 guests', true) === 5, 'Guest count embedded with dates');
    checkFacebook(facebookConversationGuests('Guests: 5', true) === 5, 'Label-first guest count');
    checkFacebook(facebookConversationGuests('October 10 to 12', true) === null, 'Date numbers are not mistaken for guests');
    checkFacebook(facebookConversationPhilippineMobile('0917 123 4567') === '+639171234567' && facebookConversationPhilippineMobile('0912345678') === '', 'Philippine mobile validation matches the website');
    checkFacebook(facebookConversationTimes('check in 2pm check out 11am') === ['check_in_time' => '14:00', 'check_out_time' => '11:00'], 'Informal AM/PM times');
    checkFacebook(facebookConversationTimes('check out time is 3pm')['check_out_time'] === '15:00', 'Natural checkout sentence');
    checkFacebook(facebookConversationTimes('11am checkin')['check_in_time'] === '11:00', 'Time before check-in label');
    checkFacebook(facebookConversationTimes("sep 15-19\n11am checkin\n09763395956")['check_in_time'] === '11:00', 'Time-first check-in survives surrounding booking lines');
    checkFacebook(facebookConversationTimes('in: 2:30 p.m. out: 11 a.m.') === ['check_in_time' => '14:30', 'check_out_time' => '11:00'], 'Punctuated shorthand times');
    checkFacebook(facebookConversationTimes('arrival 1400 departure 1100') === ['check_in_time' => '14:00', 'check_out_time' => '11:00'], 'Military times');
    checkFacebook(facebookConversationTimes('dating alas dos ng hapon, alis alas onse ng umaga') === ['check_in_time' => '14:00', 'check_out_time' => '11:00'], 'Tagalog written times');
    checkFacebook(facebookConversationTimes('chek in 2 chek out 11') === ['check_in_time' => '14:00', 'check_out_time' => '11:00'], 'Loose labels and bare-hour inference');
    checkFacebook(facebookConversationTimes('2am to 11am') === ['check_in_time' => '02:00', 'check_out_time' => '11:00'], 'Unlabelled explicit AM times remain literal');
    checkFacebook(facebookConversationTimes('2 to 11') === ['check_in_time' => '14:00', 'check_out_time' => '11:00'], 'Short bare-hour range uses booking-time inference');
    checkFacebook(facebookConversationTimes('October 2 to 11') === ['check_in_time' => null, 'check_out_time' => null], 'A date range is not mistaken for a bare time range');
    checkFacebook(facebookConversationCommand('bakc') === 'back', 'Navigation typo handling');
    checkFacebook(facebookConversationCommand('book') === null, 'Booking word is not mistaken for a command');
    checkFacebook(facebookConversationCommand('Can I talk to an admin please?') === 'staff', 'Natural staff request');
    $identity = facebookConversationIdentityContact('Name: Maria Santos, phone no: 0917 123 4567');
    checkFacebook($identity['guest_name'] === 'Maria Santos' && $identity['phone'] !== '', 'Combined loose identity and contact parsing');
    checkFacebook(facebookConversationDetails('good afternoon po, maga-ask lang po how much po rate 2 pax for 3 days and 2 nights?')['guest_name'] === '', 'Greeting is not inferred as a customer name');
    checkFacebook(facebookConversationIdentityContact('good afternoon po, charles@gmail.com')['guest_name'] === '', 'Greeting beside contact information is not inferred as a name');
    checkFacebook(facebookConversationDetails("Name: Good Afternoon\nContact: charles@gmail.com")['guest_name'] === '', 'Explicit greeting text is not accepted as a name');
    checkFacebook(facebookConversationDetails('Kate Beltrano po name ko')['guest_name'] === 'Kate Beltrano', 'Tagalog name suffix is removed from the customer name');
    checkFacebook(facebookConversationDetails('book it under the name Kate Beltrano, b.k.y.a@gmail.com')['guest_name'] === 'Kate Beltrano', 'Natural booking-name phrase');
    checkFacebook(facebookConversationDetails('Ako po si Kate Beltrano')['guest_name'] === 'Kate Beltrano', 'Tagalog name introduction is removed from the customer name');
    checkFacebook(facebookConversationNameCandidate('Kate Beltrano po ko') === 'Kate Beltrano', 'Previously saved conversational name suffix is normalized');
    checkFacebook(facebookRetryDecision(1, 429, false, false, 300)['delay'] === 300, 'Retry-After honored');
    checkFacebook(facebookRetryDecision(2, 503, false)['delay'] === 120, 'Exponential backoff');
    checkFacebook(facebookRetryDecision(5, 503, true)['status'] === 'failed', 'Retry limit');
    checkFacebook(facebookRetryDecision(1, 403, false)['status'] === 'failed', 'Permission errors not retried');
    checkFacebook(facebookRetryDecision(1, 503, true, true)['status'] === 'failed', 'Unconfirmed delivery not duplicated');
    if (!in_array(requireEnvironment('DB_HOST'), ['127.0.0.1', 'localhost'], true) || requireEnvironment('DB_NAME') !== 'odidepse_db') throw new RuntimeException('Local database required.');
    $db = database();
    $db->beginTransaction();
    $combinationStart = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+700 days');
    $combinationEnd = $combinationStart->modify('+2 days');
    $combinationOptions = facebookConversationStayOptions($db, 15, $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), null, 10);
    $bestCombination = $combinationOptions[0] ?? null;
    checkFacebook(($bestCombination['style'] ?? '') === 'combination' && (int) $bestCombination['max_guests'] === 15, 'Fifteen guests receive an exact-fit multi-room suggestion before large-group accommodation');
    $componentLabels = array_map(static fn(array $component): string => $component['quantity'] . 'x' . $component['capacity'], $bestCombination['components'] ?? []);
    sort($componentLabels);
    checkFacebook($componentLabels === ['1x10', '1x5'], 'Exact fifteen-pax suggestion clearly contains one 10-guest and one 5-guest room');
    $combinationRateText = facebookConversationOptionsText($combinationOptions, facebookDefaultRules());
    checkFacebook(str_contains($combinationRateText, '1 × 10-guest room') && str_contains($combinationRateText, '1 × 5-guest room'), 'Combination response names each room quantity and capacity');
    checkFacebook(str_contains($combinationRateText, "Room prices:\n• 1 × 10-guest room: PHP ") && str_contains($combinationRateText, "\n• 1 × 5-guest room: PHP ") && str_contains($combinationRateText, 'Combined room rate: PHP ') && str_contains($combinationRateText, 'Estimated stay total (2 nights): PHP '), 'Combination rate clearly separates every room price, nightly rate and full-stay estimate');
    $fiveGuestComponent = array_values(array_filter($bestCombination['components'], static fn(array $component): bool => (int) $component['capacity'] === 5))[0];
    $fiveGuestQuery = $db->prepare('SELECT name, details FROM resort_stays WHERE id = ?');
    $fiveGuestQuery->execute([$fiveGuestComponent['stay_id']]);
    $fiveGuestStay = $fiveGuestQuery->fetch();
    $fiveGuestDetails = json_decode($fiveGuestStay['details'], true, 32, JSON_THROW_ON_ERROR);
    $fiveGuestUnits = facebookConversationAvailableUnits($db, (int) $fiveGuestComponent['stay_id'], $fiveGuestStay['name'], $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), (int) $fiveGuestDetails['room_count'], false);
    $combinationBlocker = $db->prepare("INSERT INTO bookings (reference_code,guest_name,email,phone,check_in,check_out,guests,stay_type,stay_id,message,status) VALUES (?,?,?,?,?,?,?,?,?,?,'confirmed')");
    for ($unit = 0; $unit < $fiveGuestUnits; $unit++) $combinationBlocker->execute(['COMBO-BLOCK-' . bin2hex(random_bytes(4)), 'Combination verification', 'verify@example.test', '+639171234567', $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), 5, $fiveGuestStay['name'], $fiveGuestComponent['stay_id'], 'Combination availability test']);
    $fallbackCombinations = facebookConversationStayOptions($db, 15, $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), null, 10);
    $fallbackText = facebookConversationOptionsText($fallbackCombinations, facebookDefaultRules());
    checkFacebook(!array_filter($fallbackCombinations, static fn(array $option): bool => (bool) array_filter($option['components'] ?? [], static fn(array $component): bool => (int) $component['stay_id'] === (int) $fiveGuestComponent['stay_id'])), 'Unavailable five-guest rooms are excluded from every suggested combination');
    checkFacebook(str_contains($fallbackText, 'closest-fit combination') && str_contains($fallbackText, 'Only the available room arrangements below'), 'Fallback explains that the ideal combination is unavailable and shows only available alternatives');
    $tenGuestComponent = array_values(array_filter($bestCombination['components'], static fn(array $component): bool => (int) $component['capacity'] === 10))[0];
    $tenGuestQuery = $db->prepare('SELECT name, details FROM resort_stays WHERE id = ?');
    $tenGuestQuery->execute([$tenGuestComponent['stay_id']]);
    $tenGuestStay = $tenGuestQuery->fetch();
    $tenGuestDetails = json_decode($tenGuestStay['details'], true, 32, JSON_THROW_ON_ERROR);
    $beforePlanBooking = facebookConversationAvailableUnits($db, (int) $tenGuestComponent['stay_id'], $tenGuestStay['name'], $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), (int) $tenGuestDetails['room_count'], false);
    $planJson = json_encode([$tenGuestComponent], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    $planInsert = $db->prepare("INSERT INTO bookings (reference_code,guest_name,email,phone,check_in,check_out,guests,stay_type,stay_id,stay_plan_json,message,status) VALUES (?,?,?,?,?,?,?,?,NULL,?,?,'confirmed')");
    $planInsert->execute(['COMBO-PLAN-' . bin2hex(random_bytes(4)), 'Combination verification', 'verify@example.test', '+639171234567', $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), 10, '1 × ' . $tenGuestStay['name'], $planJson, 'Combination inventory test']);
    checkFacebook(facebookConversationAvailableUnits($db, (int) $tenGuestComponent['stay_id'], $tenGuestStay['name'], $combinationStart->format('Y-m-d'), $combinationEnd->format('Y-m-d'), (int) $tenGuestDetails['room_count'], false) === max(0, $beforePlanBooking - 1), 'Confirmed multi-room bookings consume every room listed in their structured plan');
    $chatServices = resortEntities($db, 'services', false);
    $chatService = $chatServices[0] ?? null;
    checkFacebook($chatService !== null, 'An enabled activity exists for Messenger testing');
    $availabilityStart = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+420 days');
    $availabilityEnd = $availabilityStart->modify('+3 days');
    $eligibleRows = [];
    foreach ($db->query("SELECT id,name,details FROM resort_stays WHERE enabled=1 AND archived=0 AND availability <> 'unavailable' ORDER BY sort_order,id")->fetchAll() as $stayRow) {
        $stayDetails = json_decode($stayRow['details'], true, 32, JSON_THROW_ON_ERROR);
        if (5 >= (int) ($stayDetails['min_guests'] ?? 1) && 5 <= (int) ($stayDetails['max_guests'] ?? 0) && ($stayDetails['style'] ?? 'standard') === 'standard') {
            $eligibleRows[] = $stayRow + ['max_guests' => (int) $stayDetails['max_guests'], 'room_count' => (int) ($stayDetails['room_count'] ?? 1)];
        }
    }
    usort($eligibleRows, static fn(array $a, array $b): int => [$a['max_guests'], $a['id']] <=> [$b['max_guests'], $b['id']]);
    $bestFit = $eligibleRows[0] ?? null;
    checkFacebook($bestFit !== null, 'A best-fit accommodation exists for availability testing');
    $blockingInsert = $db->prepare("INSERT INTO bookings (reference_code,guest_name,email,phone,check_in,check_out,guests,stay_type,stay_id,message,status) VALUES (?,?,?,?,?,?,?,?,?,?,'confirmed')");
    for ($room = 1; $room <= max(1, $bestFit['room_count']); $room++) {
        $blockingInsert->execute(['FB-BLOCK-' . bin2hex(random_bytes(4)), 'Availability verification', 'verify@example.test', '', $availabilityStart->format('Y-m-d'), $availabilityEnd->format('Y-m-d'), 5, $bestFit['name'], $bestFit['id'], 'Availability test']);
    }
    $alternatives = facebookConversationUnavailableAlternatives($db, 5, $availabilityStart->format('Y-m-d'), $availabilityEnd->format('Y-m-d'));
    checkFacebook($alternatives !== null && (int) $alternatives['unavailable']['id'] === (int) $bestFit['id'], 'Confirmed bookings make the best-fit accommodation unavailable');
    checkFacebook(($alternatives['options'][0]['alternative_type'] ?? '') === 'custom_dates', 'Unavailable response first accepts customer-proposed replacement dates');
    checkFacebook(count(array_filter($alternatives['options'], static fn(array $option): bool => $option['alternative_type'] === 'dates')) >= 1, 'Unavailable best-fit room offers nearby dates');
    checkFacebook(count(array_filter($alternatives['options'], static fn(array $option): bool => $option['alternative_type'] === 'upgrade' && $option['max_guests'] >= 5)) >= 1, 'Unavailable best-fit room offers a capacity-safe upgrade');
    $unavailableText = facebookConversationUnavailableText($alternatives, $availabilityStart->format('Y-m-d'), $availabilityEnd->format('Y-m-d'));
    checkFacebook(str_contains($unavailableText, 'Hi! Thank you for choosing to stay with us. 😊') && str_contains($unavailableText, 'simply send your preferred new dates'), 'Unavailable response uses the requested friendly format and accepts natural date replies');
    checkFacebook(array_filter(facebookConversationStayOptions($db, 8, $availabilityStart->format('Y-m-d'), $availabilityEnd->format('Y-m-d')), static fn(array $option): bool => $option['max_guests'] < 8) === [], 'Room suggestions never fall below the requested pax');
    $db->exec("INSERT INTO facebook_events (source,kind,guest_name,body,category) VALUES ('manual','message','Automation verification','Is a room available?','booking')");
    $id = (int) $db->lastInsertId();
    $event = ['id' => $id, 'kind' => 'message', 'category' => 'booking', 'status' => 'new'];
    checkFacebook(facebookPrepareReply($db, $event, facebookDefaultRules()), 'Reply preparation');
    checkFacebook(!facebookPrepareReply($db, $event, facebookDefaultRules()), 'Duplicate reply suppressed');
    $query = $db->prepare('SELECT status FROM facebook_jobs WHERE event_id = ?'); $query->execute([$id]);
    checkFacebook($query->fetchColumn() === 'blocked', 'Disconnected reply remains blocked');
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','456','message','Webhook verification','How much? ',CURRENT_TIMESTAMP,'rates')");
    $webhookId = (int) $db->lastInsertId();
    checkFacebook(facebookPrepareReply($db, ['id' => $webhookId, 'kind' => 'message', 'category' => 'rates', 'status' => 'new'], facebookDefaultRules(), true), 'Automatic reply queueing');
    $query = $db->prepare('SELECT status, payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$webhookId]);
    $automaticJob = $query->fetch();
    checkFacebook($automaticJob && $automaticJob['status'] === 'pending', 'Verified webhook reply is ready for delivery');
    checkFacebook(str_contains($automaticJob['payload'], facebookAutomaticReplyNotice()), 'Automatic reply includes system-generated notice');
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','handoff-test','message','Handoff verification','ADMIN',CURRENT_TIMESTAMP,'general')");
    $handoffEventId = (int) $db->lastInsertId();
    checkFacebook(facebookQueueReply($db, $handoffEventId, facebookDefaultRules()['guided_replies']['handoff'], true, false), 'Admin handoff reply queueing');
    $query = $db->prepare('SELECT payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$handoffEventId]);
    $handoffPayload = (string) $query->fetchColumn();
    checkFacebook(str_contains($handoffPayload, 'handoff_reply') && !str_contains($handoffPayload, facebookAutomaticReplyNotice()), 'Admin handoff omits the redundant automatic notice');
    $takeoverSender = 'takeover-' . bin2hex(random_bytes(4));
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','{$takeoverSender}','message','Takeover verification','Initial inquiry',CURRENT_TIMESTAMP,'general')");
    $takeoverStartEventId = (int) $db->lastInsertId();
    $insertTakeoverConversation = $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json,last_event_id) VALUES ('123',?,'idle','{}',?)");
    $insertTakeoverConversation->execute([$takeoverSender, $takeoverStartEventId]);
    facebookStartHumanTakeover($db, '123', $takeoverSender, $takeoverStartEventId);
    $insertTakeoverMessage = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123',?,'message','Takeover verification','What amenities do you have?',CURRENT_TIMESTAMP,'amenities')");
    $insertTakeoverMessage->execute([$takeoverSender]);
    $silentTakeoverReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => '123', 'sender_id' => $takeoverSender, 'body' => 'What amenities do you have?', 'category' => 'amenities'], facebookDefaultRules());
    checkFacebook($silentTakeoverReply === '', 'Successful staff reply pauses chatbot responses');
    $expiredTakeover = json_encode(['human_takeover_until' => time() - 1], JSON_THROW_ON_ERROR);
    $db->prepare('UPDATE facebook_conversations SET data_json = ? WHERE page_id = ? AND sender_id = ?')->execute([$expiredTakeover, '123', $takeoverSender]);
    $insertTakeoverMessage->execute([$takeoverSender]);
    $resumedTakeoverReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => '123', 'sender_id' => $takeoverSender, 'body' => 'What amenities do you have?', 'category' => 'amenities'], facebookDefaultRules());
    checkFacebook($resumedTakeoverReply !== '', 'Chatbot resumes for a later inquiry after human takeover expires');
    $db->exec("INSERT INTO facebook_events (source,kind,guest_name,body,category,needs_attention) VALUES ('manual','message','Complaint verification','I have a complaint','complaint',1)");
    $complaintId = (int) $db->lastInsertId();
    checkFacebook(facebookPrepareReply($db, ['id' => $complaintId, 'kind' => 'message', 'category' => 'complaint', 'status' => 'new'], facebookDefaultRules()), 'Complaint acknowledgement');
    $query = $db->prepare('SELECT payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$complaintId]);
    checkFacebook(str_contains((string) $query->fetchColumn(), 'admin'), 'Complaint acknowledgement directs to admin');
    facebookAudit($db, null, 'verification', 'event', $id);
    $query = $db->prepare('SELECT COUNT(*) FROM facebook_audit WHERE entity_id = ? AND action = ?'); $query->execute([$id, 'verification']);
    checkFacebook((int) $query->fetchColumn() === 1, 'Audit persistence');
    checkFacebook(is_file(stayPhotoDeliveryPath('room_0')), 'Bundled room photo can be resolved for Messenger delivery');
    $db->exec("INSERT INTO facebook_webhook_state (id, verified_host) VALUES (1, 'preview.example.com') ON DUPLICATE KEY UPDATE verified_host = VALUES(verified_host)");
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','photo-page','photo-sender','message','Photo verification','Photo test',CURRENT_TIMESTAMP,'booking')");
    $photoEventId = (int) $db->lastInsertId();
    $photoData = json_encode(['room_photo_event_id' => $photoEventId, 'room_photos' => ['room_0', 'room_1'], 'stay_name' => '8-guest room', 'stay_suggested' => true, 'guests' => 8], JSON_THROW_ON_ERROR);
    $insertPhotoConversation = $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json,last_event_id) VALUES ('photo-page','photo-sender','awaiting_confirmation',?,?)");
    $insertPhotoConversation->execute([$photoData, $photoEventId]);
    checkFacebook(facebookQueueReply($db, $photoEventId, 'Suggested room summary', true), 'Suggested-room text queues before photos');
    checkFacebook(facebookQueueNativeRoomPhotos($db, $photoEventId, 'photo-page', 'photo-sender') === 3, 'Suggested native room photos and caption are queued');
    $query = $db->prepare('SELECT payload, status, error_code FROM facebook_jobs WHERE event_id = ? ORDER BY id'); $query->execute([$photoEventId]);
    $photoJobs = $query->fetchAll();
    checkFacebook(count($photoJobs) === 4 && str_contains($photoJobs[1]['payload'], 'room_photo') && $photoJobs[1]['status'] === 'pending' && $photoJobs[2]['status'] === 'blocked' && $photoJobs[2]['error_code'] === 'awaiting_previous_photo' && str_contains($photoJobs[3]['payload'], 'room_photo_caption') && str_contains($photoJobs[3]['payload'], 'suggested 8-guest room for your group of 8 guests') && str_contains($photoJobs[3]['payload'], 'Reply CONFIRM to submit') && str_contains($photoJobs[3]['payload'], 'Reply BACK to edit or CANCEL to stop') && !str_contains($photoJobs[3]['payload'], facebookAutomaticReplyNotice()) && $photoJobs[3]['status'] === 'blocked', 'Native room photos are ordered before a clean dependent contextual caption with confirmation controls');

    $restartSender = 'restart-test-' . bin2hex(random_bytes(4));
    $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json) VALUES ('conversation-page',?,'awaiting_booking_details','{}')")->execute([$restartSender]);
    $restartEvent = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','conversation-page',?,'message','Messenger guest','RESTART',CURRENT_TIMESTAMP,'general')");
    $restartEvent->execute([$restartSender]);
    $restartReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => 'conversation-page', 'sender_id' => $restartSender, 'guest_name' => 'Messenger guest', 'body' => 'RESTART', 'category' => 'general'], facebookDefaultRules());
    checkFacebook($restartReply === facebookDefaultRules()['templates']['general'], 'Restart resets the flow and sends the general response');
    $restartState = $db->prepare('SELECT state FROM facebook_conversations WHERE page_id = ? AND sender_id = ?');
    $restartState->execute(['conversation-page', $restartSender]);
    checkFacebook($restartState->fetchColumn() === 'idle', 'Restart returns the conversation to a fresh inquiry state');

    $overrideSender = 'name-override-' . bin2hex(random_bytes(4));
    $overrideData = json_encode(['guest_name' => 'Gabriel Martinez', 'guest_name_source' => 'facebook_profile', 'facebook_profile_name' => 'Gabriel Martinez'], JSON_THROW_ON_ERROR);
    $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json) VALUES ('conversation-page',?,'awaiting_booking_details',?)")->execute([$overrideSender, $overrideData]);
    $overrideBody = 'check out time is 3pm, book it under the name Kate Beltrano, b.k.y.a@gmail.com, 0912345678';
    $overrideEvent = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','conversation-page',?,'message','Gabriel Martinez',?,CURRENT_TIMESTAMP,'booking')");
    $overrideEvent->execute([$overrideSender, $overrideBody]);
    $overrideReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => 'conversation-page', 'sender_id' => $overrideSender, 'guest_name' => 'Gabriel Martinez', 'body' => $overrideBody, 'category' => 'booking'], facebookDefaultRules());
    checkFacebook(str_contains($overrideReply, 'Check-out time: 3:00 PM') && str_contains($overrideReply, 'Name: Kate Beltrano'), 'Customer booking name and natural checkout override Facebook profile data');
    $overrideState = $db->prepare('SELECT data_json FROM facebook_conversations WHERE page_id = ? AND sender_id = ?');
    $overrideState->execute(['conversation-page', $overrideSender]);
    $savedOverride = json_decode((string) $overrideState->fetchColumn(), true, 32, JSON_THROW_ON_ERROR);
    checkFacebook(($savedOverride['guest_name'] ?? '') === 'Kate Beltrano' && ($savedOverride['guest_name_source'] ?? '') === 'customer', 'Explicit customer name remains authoritative over profile name');
    $timeFirstEvent = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','conversation-page',?,'message','Gabriel Martinez','11am checkin',CURRENT_TIMESTAMP,'general')");
    $timeFirstEvent->execute([$overrideSender]);
    $timeFirstReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => 'conversation-page', 'sender_id' => $overrideSender, 'guest_name' => 'Gabriel Martinez', 'body' => '11am checkin', 'category' => 'general'], facebookDefaultRules());
    checkFacebook(str_contains($timeFirstReply, 'Check-in time: 11:00 AM'), 'Messenger flow accepts time before check-in label');

    $sender = 'conversation-test-' . bin2hex(random_bytes(4));
    $page = 'conversation-page';
    $addMessage = static function (string $body, string $category) use ($db, $sender, $page): array {
        $insert = $db->prepare("INSERT INTO facebook_events (source, page_id, sender_id, kind, guest_name, body, last_customer_message_at, category) VALUES ('facebook', ?, ?, 'message', 'Conversation verification', ?, CURRENT_TIMESTAMP, ?)");
        $insert->execute([$page, $sender, $body, $category]);
        return ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $sender, 'body' => $body, 'category' => $category];
    };
    $checkIn = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+180 days');
    $checkOut = $checkIn->modify('+2 days');
    $directSender = 'direct-details-' . bin2hex(random_bytes(4));
    $directBody = "Dates: {$checkIn->format('F j')} to {$checkOut->format('j, Y')}\nCheck in: 2 PM\nCheck out: 11 AM\nGuests: 5\nName: Maria Santos\nEmail: maria@example.test\nPhone: 09171234567";
    $directCategory = facebookCategory($directBody);
    $directInsert = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook',?,?, 'message','Messenger guest',?,CURRENT_TIMESTAMP,?)");
    $directInsert->execute([$page, $directSender, $directBody, $directCategory]);
    $directReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $directSender, 'guest_name' => 'Messenger guest', 'body' => $directBody, 'category' => $directCategory], facebookDefaultRules());
    checkFacebook($directCategory === 'booking' && str_contains($directReply, '5 guests') && str_contains($directReply, 'maria@example.test') && str_contains($directReply, '+639171234567') && str_contains($directReply, 'PENDING'), 'Complete labelled details start and complete Messenger booking flow without saying booking: ' . $directCategory . ' / ' . $directReply);
    $mobileRequiredSender = 'mobile-required-' . bin2hex(random_bytes(4));
    $mobileRequiredBody = "Dates: {$checkIn->format('F j')} to {$checkOut->format('j, Y')}\nCheck in: 2 PM\nCheck out: 11 AM\nGuests: 5\nName: Maria Santos\nEmail: maria@example.test";
    $directInsert->execute([$page, $mobileRequiredSender, $mobileRequiredBody, 'booking']);
    $mobileRequiredReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $mobileRequiredSender, 'guest_name' => 'Messenger guest', 'body' => $mobileRequiredBody, 'category' => 'booking'], facebookDefaultRules());
    checkFacebook(str_contains($mobileRequiredReply, 'Mobile: Needed') && !str_contains($mobileRequiredReply, 'PENDING'), 'Messenger requires a Philippine mobile number even when email is present');
    $combinationSender = 'combination-booking-' . bin2hex(random_bytes(4));
    $combinationBody = "Dates: {$checkIn->format('F j')} to {$checkOut->format('j, Y')}\nCheck in: 2 PM\nCheck out: 11 AM\nGuests: 15\nName: Maria Santos\nEmail: maria@example.test\nPhone: 09171234567";
    $directInsert->execute([$page, $combinationSender, $combinationBody, 'booking']);
    $combinationReview = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $combinationSender, 'guest_name' => 'Messenger guest', 'body' => $combinationBody, 'category' => 'booking'], facebookDefaultRules());
    checkFacebook(str_contains($combinationReview, '1 × 10-guest room + 1 × 5-guest room'), 'Messenger review clearly identifies the selected fifteen-pax room combination');
    $directInsert->execute([$page, $combinationSender, 'CONFIRM', 'general']);
    $combinationConfirmEventId = (int) $db->lastInsertId();
    facebookConversationReply($db, ['id' => $combinationConfirmEventId, 'page_id' => $page, 'sender_id' => $combinationSender, 'guest_name' => 'Messenger guest', 'body' => 'CONFIRM', 'category' => 'general'], facebookDefaultRules());
    $combinationBookingQuery = $db->prepare('SELECT b.stay_type, b.stay_plan_json, b.status FROM facebook_events e JOIN bookings b ON b.id = e.booking_id WHERE e.id = ?');
    $combinationBookingQuery->execute([$combinationConfirmEventId]);
    $combinationBooking = $combinationBookingQuery->fetch();
    checkFacebook($combinationBooking && $combinationBooking['status'] === 'pending' && count(json_decode((string) $combinationBooking['stay_plan_json'], true, 32, JSON_THROW_ON_ERROR)) === 2, 'Messenger confirmation stores one pending booking with its structured room plan');
    checkFacebook(facebookConversationGuests('8', true) === 8 && facebookConversationGuests('October 8 to 10', true) === null, 'Plain guest-count follow-up is retained without treating dates as guest counts');
    $unlabelledDetails = facebookConversationDetails("September 15 18\n5\nCharles Martinez\n09763395956");
    checkFacebook($unlabelledDetails['guests'] === 5 && $unlabelledDetails['phone'] === '09763395956', 'Guest count on its own line is read from a combined customer reply');
    $roomCapacityDetails = facebookConversationDetails("September 15 18\n5\n8 guest room\nCharles Martinez\n09763395956");
    checkFacebook($roomCapacityDetails['guests'] === 5, 'Room capacity is not mistaken for the customer guest count');
    $initialReply = facebookConversationReply($db, $addMessage('I want to book', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($initialReply, facebookDefaultRules()['guided_replies']['start']) && str_contains($initialReply, facebookDefaultRules()['guided_replies']['ask_booking_details']) && !str_contains($initialReply, 'Name: Needed'), 'Empty booking start gives friendly shared instructions instead of an empty checklist');
    $sideReply = facebookConversationReply($db, $addMessage('What amenities do you have?', 'amenities'), facebookDefaultRules());
    checkFacebook(str_contains($sideReply, 'amenities include') && !str_contains($sideReply, 'progress is saved') && !str_contains($sideReply, 'CONFIRM'), 'Side question is answered without booking-flow instructions');
    $allDetails = "Dates: {$checkIn->format('F j')} to {$checkOut->format('j, Y')}\nCheck in: 2 PM\nCheck out: 11 AM\nGuests: 2 guests\nRoom: BEST FIT\nName: Maria Santos\nEmail: maria@example.test\nPhone: 0917 123 4567\nActivities: {$chatService['name']}\nNotes: Birthday stay";
    $summaryReply = facebookConversationReply($db, $addMessage($allDetails, 'general'), facebookDefaultRules());
    checkFacebook(str_contains($summaryReply, 'PENDING') && str_contains($summaryReply, 'Check-in 2:00 PM · Check-out 11:00 AM') && str_contains($summaryReply, 'Suggested room:') && str_contains($summaryReply, $chatService['name']) && str_contains($summaryReply, 'Birthday stay'), 'Messenger summary includes shared activities and notes');
    $shortcutDates = $checkIn->modify('+10 days');
    $shortcutEnd = $shortcutDates->modify('+4 days');
    $shortcutReply = facebookConversationReply($db, $addMessage('inquire p ako for ' . $shortcutDates->format('M j') . '-' . $shortcutEnd->format('j') . ', in 2pm out 11am', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($shortcutReply, 'Dates: ' . $shortcutDates->format('M j')) && str_contains($shortcutReply, 'Total pax: NOT PROVIDED YET') && !str_contains($shortcutReply, 'exactly CONFIRM'), 'Short casual date inquiry revises a confirmation instead of triggering its invalid-answer reminder');
    $shortcutSummary = facebookConversationReply($db, $addMessage('2 pax', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($shortcutSummary, 'PENDING') && str_contains($shortcutSummary, 'Suggested room:'), 'Pax follow-up completes the revised booking review');
    $rateSideReply = facebookConversationReply($db, $addMessage('What are your rates?', 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($rateSideReply, 'rates') && !str_contains($rateSideReply, 'progress is saved') && !str_contains($rateSideReply, 'CONFIRM'), 'Rate side question during confirmation stays informational and omits booking controls');
    $confirmation = $addMessage('CONFIRM', 'general');
    checkFacebook(str_contains(facebookConversationReply($db, $confirmation, facebookDefaultRules()), 'not confirmed'), 'Confirmation creates pending request only');
    $query = $db->prepare("SELECT b.status, e.needs_attention FROM facebook_events e JOIN bookings b ON b.id = e.booking_id WHERE e.id = ?");
    $query->execute([$confirmation['id']]);
    $created = $query->fetch();
    checkFacebook($created && $created['status'] === 'pending' && (int) $created['needs_attention'] === 1, 'Pending booking alerts staff');
    $createdBookingId = (int) $db->query('SELECT MAX(id) FROM bookings')->fetchColumn();
    $createdOptionalQuery = $db->prepare('SELECT service_id, service_name, message FROM bookings WHERE id = ?');
    $createdOptionalQuery->execute([$createdBookingId]);
    $createdOptional = $createdOptionalQuery->fetch();
    checkFacebook((int) $createdOptional['service_id'] === (int) $chatService['id'] && $createdOptional['service_name'] === $chatService['name'] && str_contains($createdOptional['message'], 'Requested activities: ' . $chatService['name']) && str_contains($createdOptional['message'], 'Guest notes: Birthday stay'), 'Messenger pending booking saves activity and notes');
    $bookingCount = (int) $db->query('SELECT COUNT(*) FROM bookings')->fetchColumn();
    $editCheckIn = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+240 days');
    $editCheckOut = $editCheckIn->modify('+2 days');
    $newRequest = facebookConversationReply($db, $addMessage($editCheckIn->format('F j') . ' to ' . $editCheckOut->format('j, Y') . ' for 5 guests', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($newRequest, "I'll update your pending request") && str_contains($newRequest, 'PENDING'), 'One message produces a pending-booking update summary');
    $updatedReply = facebookConversationReply($db, $addMessage('confirm', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($updatedReply, 'was updated'), 'Customer confirmation updates the pending request');
    checkFacebook((int) $db->query('SELECT COUNT(*) FROM bookings')->fetchColumn() === $bookingCount, 'Pending update does not create another booking');
    $query = $db->prepare('SELECT check_in, check_out, guests, message, status FROM bookings WHERE id = ?'); $query->execute([$createdBookingId]);
    $updated = $query->fetch();
    checkFacebook($updated && $updated['check_in'] === $editCheckIn->format('Y-m-d') && $updated['check_out'] === $editCheckOut->format('Y-m-d') && (int) $updated['guests'] === 5 && str_contains($updated['message'], 'Preferred arrival: 14:00') && str_contains($updated['message'], 'Preferred departure: 11:00') && $updated['status'] === 'pending', 'Pending booking details and times updated in place');
    $revisedRateDates = $editCheckIn->modify('+30 days');
    $revisedRateEnd = $revisedRateDates->modify('+3 days');
    $partialRateReply = facebookConversationReply($db, $addMessage('Inquire po rates for ' . $revisedRateDates->format('F j') . ' to ' . $revisedRateEnd->format('j'), 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($partialRateReply, 'Dates: ' . $revisedRateDates->format('M j')) && str_contains($partialRateReply, 'Total pax: NOT PROVIDED YET') && str_contains($partialRateReply, 'TOTAL NUMBER OF PAX') && str_contains($partialRateReply, 'Example: 5 pax') && !str_contains($partialRateReply, 'Ilang tao') && str_contains($partialRateReply, 'Name: Maria Santos'), 'Partial rate inquiry clearly asks for the missing pax count');
    $completedRateReply = facebookConversationReply($db, $addMessage('for 5 pax, check in 2pm check out 11am', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($completedRateReply, 'PENDING') && str_contains($completedRateReply, 'Suggested room:') && !str_contains($completedRateReply, 'exactly CONFIRM'), 'Missing guest follow-up produces the revised booking review');

    $rateSender = 'rate-test-' . bin2hex(random_bytes(4));
    $addRateMessage = static function (string $body, string $category) use ($db, $rateSender, $page): array {
        $insert = $db->prepare("INSERT INTO facebook_events (source, page_id, sender_id, kind, guest_name, body, last_customer_message_at, category) VALUES ('facebook', ?, ?, 'message', 'Rate verification', ?, CURRENT_TIMESTAMP, ?)");
        $insert->execute([$page, $rateSender, $body, $category]);
        return ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $rateSender, 'body' => $body, 'category' => $category];
    };
    $initialRateReply = facebookConversationReply($db, $addRateMessage('How much are your rooms?', 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($initialRateReply, 'Dates: Needed') && str_contains($initialRateReply, 'Total pax: NOT PROVIDED YET'), 'Rate inquiry asks only for dates and pax');
    $rateReply = facebookConversationReply($db, $addRateMessage($checkIn->format('F j') . ' to ' . $checkOut->format('j, Y') . ' for 5 guests', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($rateReply, 'PHP') && str_contains($rateReply, 'Want to book?'), 'One rate-details message returns suitable prices');
    $db->rollBack();
    echo "Passed: classification, profile names, reply deduplication, complaint acknowledgement, guided booking state, side questions, pending-only creation and updates, staff alerting, automatic disclosure, automatic queueing, blocked manual delivery, retry policy, and audit persistence. Test rows rolled back.\n";
} catch (Throwable $error) {
    if (isset($db) && $db->inTransaction()) $db->rollBack();
    fwrite(STDERR, 'Facebook verification failed: ' . ($error instanceof PDOException ? 'Database operation failed.' : $error->getMessage()) . "\n");
    exit(1);
}
