<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once dirname(__DIR__) . '/includes/facebook-automations.php';
require_once dirname(__DIR__) . '/includes/stay-photos.php';
function checkFacebook(bool $condition, string $message): void {
    if (!$condition) throw new RuntimeException($message);
}
try {
    checkFacebook(facebookCategory('Magkano po ang room?') === 'rates', 'Filipino rates classification');
    checkFacebook(facebookCategory('Pwede po ba magpareserve?', true, facebookDefaultRules()['keywords']) === 'booking', 'Editable Tagalog booking classification');
    checkFacebook(facebookCategory('Malapit ba kayo sa bayan?', true, facebookDefaultRules()['keywords']) === 'location', 'Editable Tagalog location classification');
    checkFacebook(facebookCategory('This is a separate question') === 'general', 'Keyword boundaries avoid partial-word matches');
    checkFacebook(facebookCategory('Is a room avalable next weekend?') === 'booking', 'Conservative booking typo matching');
    checkFacebook(facebookCategory('What amnities do you have?') === 'amenities', 'Conservative amenity typo matching');
    checkFacebook(facebookCategory('Please send your locaton') === 'location', 'Conservative location typo matching');
    checkFacebook(facebookCategory('Next weekend for 5 guests') === 'booking', 'Dates plus party size imply booking intent');
    checkFacebook(facebookCategory('inquire p ako for sep 15-19') === 'booking', 'Short casual inquiry with dates implies booking intent');
    checkFacebook(str_contains(facebookDefaultRules()['templates']['location'], 'google.com/maps/'), 'Location reply includes Google Maps');
    checkFacebook(str_contains(facebookDefaultRules()['templates']['rates'], 'Leave this blank if you want us to suggest the best fit') && str_contains(facebookDefaultRules()['templates']['rates'], 'Requested activities (optional) — ATV, banana boat, or jet ski rental'), 'Rates template explains optional accommodation and activities without repetition');
    checkFacebook(facebookCategory('Booking complaint: refund please') === 'complaint', 'Complaint priority');
    checkFacebook(facebookCategory('Is there availability?', false) === 'general', 'Disabled classification');
    checkFacebook(facebookProfileName(['name' => '  Maria   Santos  ']) === 'Maria Santos', 'Messenger profile name normalization');
    checkFacebook(facebookProfileName(['name' => '']) === null, 'Empty Messenger profile name fallback');
    checkFacebook(facebookWebhookMessageBody(['text' => 'Hello 😊'])['body'] === 'Hello 😊', 'Unicode emoji text is preserved');
    checkFacebook(facebookWebhookMessageBody(['sticker_id' => 1])['body'] === '👍', 'Messenger quick-like sticker is displayed without triggering a reply');
    $photoMessage = facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'https://scontent.example.test/photo.jpg']]]]);
    checkFacebook($photoMessage['body'] === '📷 Photo received' && $photoMessage['attachment_type'] === 'image' && $photoMessage['attachment_url'] === 'https://scontent.example.test/photo.jpg' && !$photoMessage['automatic_reply'], 'Incoming photo URL is retained without triggering a reply');
    $stickerMessage = facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'https://scontent.xx.fbcdn.net/v/t39.1997-6/thumb.png']]]]);
    checkFacebook($stickerMessage['body'] === '👍' && $stickerMessage['attachment_type'] === 'sticker', 'Messenger sticker image is identified for compact display');
    checkFacebook(facebookWebhookMessageBody(['attachments' => [['type' => 'image', 'payload' => ['url' => 'javascript:alert(1)']]]])['attachment_url'] === null, 'Unsafe attachment URL is rejected');
    $customRules = facebookDefaultRules();
    $customRules['guided_replies']['ask_guests'] = 'CUSTOM GUEST QUESTION';
    checkFacebook(facebookConversationPrompt('awaiting_guests', $customRules) === 'CUSTOM GUEST QUESTION', 'Guided reply customization');
    checkFacebook(str_contains(facebookGuidedReply($customRules, 'pending_created', ['reference' => 'OD-TEST']), 'OD-TEST'), 'Guided placeholder replacement');
    checkFacebook(facebookConversationDates('next weekend') !== null, 'Natural next-weekend dates');
    checkFacebook(facebookConversationDates('October 10 to 12') !== null, 'Natural month-name dates');
    checkFacebook(facebookConversationDates('next wekend') !== null, 'Misspelled relative dates');
    checkFacebook(facebookConversationDates('Octber 10') !== null, 'Misspelled single-date stay');
    checkFacebook(facebookConversationGuests('2 adults and 3 kids') === 5, 'Combined adult and child count');
    checkFacebook(facebookConversationGuests('lima kami') === 5, 'Written Tagalog guest count');
    checkFacebook(facebookConversationGuests('fiev people') === 5, 'Conservative written-number typo');
    checkFacebook(facebookConversationGuests('October 10 to 12 for 5 guests', true) === 5, 'Guest count embedded with dates');
    checkFacebook(facebookConversationGuests('October 10 to 12', true) === null, 'Date numbers are not mistaken for guests');
    checkFacebook(facebookConversationCommand('bakc') === 'back', 'Navigation typo handling');
    checkFacebook(facebookConversationCommand('book') === null, 'Booking word is not mistaken for a command');
    checkFacebook(facebookConversationCommand('Can I talk to an admin please?') === 'staff', 'Natural staff request');
    $identity = facebookConversationIdentityContact('Name: Maria Santos, phone no: 0917 123 4567');
    checkFacebook($identity['guest_name'] === 'Maria Santos' && $identity['phone'] !== '', 'Combined loose identity and contact parsing');
    checkFacebook(facebookRetryDecision(1, 429, false, false, 300)['delay'] === 300, 'Retry-After honored');
    checkFacebook(facebookRetryDecision(2, 503, false)['delay'] === 120, 'Exponential backoff');
    checkFacebook(facebookRetryDecision(5, 503, true)['status'] === 'failed', 'Retry limit');
    checkFacebook(facebookRetryDecision(1, 403, false)['status'] === 'failed', 'Permission errors not retried');
    checkFacebook(facebookRetryDecision(1, 503, true, true)['status'] === 'failed', 'Unconfirmed delivery not duplicated');
    if (!in_array(requireEnvironment('DB_HOST'), ['127.0.0.1', 'localhost'], true) || requireEnvironment('DB_NAME') !== 'odidepse_db') throw new RuntimeException('Local database required.');
    $db = database();
    $db->beginTransaction();
    $db->exec("INSERT INTO facebook_events (source,kind,guest_name,body,category) VALUES ('manual','message','Automation verification','Is a room available?','booking')");
    $id = (int) $db->lastInsertId();
    $event = ['id' => $id, 'kind' => 'message', 'category' => 'booking', 'status' => 'new'];
    checkFacebook(facebookPrepareReply($db, $event, facebookDefaultRules()), 'Reply preparation');
    checkFacebook(!facebookPrepareReply($db, $event, facebookDefaultRules()), 'Duplicate reply suppressed');
    $query = $db->prepare('SELECT status FROM facebook_jobs WHERE event_id = ?'); $query->execute([$id]);
    checkFacebook($query->fetchColumn() === 'blocked', 'Disconnected reply remains blocked');
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','456','message','Webhook verification','How much? ',CURRENT_TIMESTAMP,'rates')");
    $webhookId = (int) $db->lastInsertId();
    checkFacebook(facebookPrepareReply($db, ['id' => $webhookId, 'kind' => 'message', 'category' => 'rates', 'status' => 'new'], facebookDefaultRules(), true), 'Automatic reply queueing');
    $query = $db->prepare('SELECT status, payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$webhookId]);
    $automaticJob = $query->fetch();
    checkFacebook($automaticJob && $automaticJob['status'] === 'pending', 'Verified webhook reply is ready for delivery');
    checkFacebook(str_contains($automaticJob['payload'], facebookAutomaticReplyNotice()), 'Automatic reply includes system-generated notice');
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','handoff-test','message','Handoff verification','ADMIN',CURRENT_TIMESTAMP,'general')");
    $handoffEventId = (int) $db->lastInsertId();
    checkFacebook(facebookQueueReply($db, $handoffEventId, facebookDefaultRules()['guided_replies']['handoff'], true, false), 'Admin handoff reply queueing');
    $query = $db->prepare('SELECT payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$handoffEventId]);
    $handoffPayload = (string) $query->fetchColumn();
    checkFacebook(str_contains($handoffPayload, 'handoff_reply') && !str_contains($handoffPayload, facebookAutomaticReplyNotice()), 'Admin handoff omits the redundant automatic notice');
    $takeoverSender = 'takeover-' . bin2hex(random_bytes(4));
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123','{$takeoverSender}','message','Takeover verification','Initial inquiry',CURRENT_TIMESTAMP,'general')");
    $takeoverStartEventId = (int) $db->lastInsertId();
    $insertTakeoverConversation = $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json,last_event_id) VALUES ('123',?,'idle','{}',?)");
    $insertTakeoverConversation->execute([$takeoverSender, $takeoverStartEventId]);
    facebookStartHumanTakeover($db, '123', $takeoverSender, $takeoverStartEventId);
    $insertTakeoverMessage = $db->prepare("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','123',?,'message','Takeover verification','What amenities do you have?',CURRENT_TIMESTAMP,'amenities')");
    $insertTakeoverMessage->execute([$takeoverSender]);
    $silentTakeoverReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => '123', 'sender_id' => $takeoverSender, 'body' => 'What amenities do you have?', 'category' => 'amenities'], facebookDefaultRules());
    checkFacebook($silentTakeoverReply === '', 'Successful staff reply pauses chatbot responses');
    $expiredTakeover = json_encode(['human_takeover_until' => time() - 1], JSON_THROW_ON_ERROR);
    $db->prepare('UPDATE facebook_conversations SET data_json = ? WHERE page_id = ? AND sender_id = ?')->execute([$expiredTakeover, '123', $takeoverSender]);
    $insertTakeoverMessage->execute([$takeoverSender]);
    $resumedTakeoverReply = facebookConversationReply($db, ['id' => (int) $db->lastInsertId(), 'page_id' => '123', 'sender_id' => $takeoverSender, 'body' => 'What amenities do you have?', 'category' => 'amenities'], facebookDefaultRules());
    checkFacebook($resumedTakeoverReply !== '', 'Chatbot resumes for a later inquiry after human takeover expires');
    $db->exec("INSERT INTO facebook_events (source,kind,guest_name,body,category,needs_attention) VALUES ('manual','message','Complaint verification','I have a complaint','complaint',1)");
    $complaintId = (int) $db->lastInsertId();
    checkFacebook(facebookPrepareReply($db, ['id' => $complaintId, 'kind' => 'message', 'category' => 'complaint', 'status' => 'new'], facebookDefaultRules()), 'Complaint acknowledgement');
    $query = $db->prepare('SELECT payload FROM facebook_jobs WHERE event_id = ?'); $query->execute([$complaintId]);
    checkFacebook(str_contains((string) $query->fetchColumn(), 'admin'), 'Complaint acknowledgement directs to admin');
    facebookAudit($db, null, 'verification', 'event', $id);
    $query = $db->prepare('SELECT COUNT(*) FROM facebook_audit WHERE entity_id = ? AND action = ?'); $query->execute([$id, 'verification']);
    checkFacebook((int) $query->fetchColumn() === 1, 'Audit persistence');
    checkFacebook(is_file(stayPhotoDeliveryPath('room_0')), 'Bundled room photo can be resolved for Messenger delivery');
    $db->exec("INSERT INTO facebook_webhook_state (id, verified_host) VALUES (1, 'preview.example.com') ON DUPLICATE KEY UPDATE verified_host = VALUES(verified_host)");
    $db->exec("INSERT INTO facebook_events (source,page_id,sender_id,kind,guest_name,body,last_customer_message_at,category) VALUES ('facebook','photo-page','photo-sender','message','Photo verification','Photo test',CURRENT_TIMESTAMP,'booking')");
    $photoEventId = (int) $db->lastInsertId();
    $photoData = json_encode(['room_photo_event_id' => $photoEventId, 'room_photos' => ['room_0', 'room_1'], 'stay_name' => '8-guest room', 'stay_suggested' => true, 'guests' => 8], JSON_THROW_ON_ERROR);
    $insertPhotoConversation = $db->prepare("INSERT INTO facebook_conversations (page_id,sender_id,state,data_json,last_event_id) VALUES ('photo-page','photo-sender','awaiting_confirmation',?,?)");
    $insertPhotoConversation->execute([$photoData, $photoEventId]);
    checkFacebook(facebookQueueReply($db, $photoEventId, 'Suggested room summary', true), 'Suggested-room text queues before photos');
    checkFacebook(facebookQueueNativeRoomPhotos($db, $photoEventId, 'photo-page', 'photo-sender') === 3, 'Suggested native room photos and caption are queued');
    $query = $db->prepare('SELECT payload, status, error_code FROM facebook_jobs WHERE event_id = ? ORDER BY id'); $query->execute([$photoEventId]);
    $photoJobs = $query->fetchAll();
    checkFacebook(count($photoJobs) === 4 && str_contains($photoJobs[1]['payload'], 'room_photo') && $photoJobs[1]['status'] === 'pending' && $photoJobs[2]['status'] === 'blocked' && $photoJobs[2]['error_code'] === 'awaiting_previous_photo' && str_contains($photoJobs[3]['payload'], 'room_photo_caption') && str_contains($photoJobs[3]['payload'], 'suggested 8-guest room for your group of 8 guests') && str_contains($photoJobs[3]['payload'], 'Reply CONFIRM to submit') && str_contains($photoJobs[3]['payload'], 'Reply BACK to edit or CANCEL to stop') && !str_contains($photoJobs[3]['payload'], facebookAutomaticReplyNotice()) && $photoJobs[3]['status'] === 'blocked', 'Native room photos are ordered before a clean dependent contextual caption with confirmation controls');

    $sender = 'conversation-test-' . bin2hex(random_bytes(4));
    $page = 'conversation-page';
    $addMessage = static function (string $body, string $category) use ($db, $sender, $page): array {
        $insert = $db->prepare("INSERT INTO facebook_events (source, page_id, sender_id, kind, guest_name, body, last_customer_message_at, category) VALUES ('facebook', ?, ?, 'message', 'Conversation verification', ?, CURRENT_TIMESTAMP, ?)");
        $insert->execute([$page, $sender, $body, $category]);
        return ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $sender, 'body' => $body, 'category' => $category];
    };
    $checkIn = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+180 days');
    $checkOut = $checkIn->modify('+2 days');
    checkFacebook(facebookConversationGuests('8', true) === 8 && facebookConversationGuests('October 8 to 10', true) === null, 'Plain guest-count follow-up is retained without treating dates as guest counts');
    $unlabelledDetails = facebookConversationDetails("September 15 18\n5\nCharles Martinez\n09763395956");
    checkFacebook($unlabelledDetails['guests'] === 5 && $unlabelledDetails['phone'] === '09763395956', 'Guest count on its own line is read from a combined customer reply');
    $roomCapacityDetails = facebookConversationDetails("September 15 18\n5\n8 guest room\nCharles Martinez\n09763395956");
    checkFacebook($roomCapacityDetails['guests'] === 5, 'Room capacity is not mistaken for the customer guest count');
    $initialReply = facebookConversationReply($db, $addMessage('I want to book', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($initialReply, 'Please send only:') && str_contains($initialReply, 'Total pax: NOT PROVIDED YET') && str_contains($initialReply, 'Name: Needed'), 'Booking shows received and missing details together');
    $sideReply = facebookConversationReply($db, $addMessage('What amenities do you have?', 'amenities'), facebookDefaultRules());
    checkFacebook(str_contains($sideReply, 'amenities include') && !str_contains($sideReply, 'progress is saved') && !str_contains($sideReply, 'CONFIRM'), 'Side question is answered without booking-flow instructions');
    $allDetails = "Dates: {$checkIn->format('F j')} to {$checkOut->format('j, Y')}\nGuests: 2 guests\nRoom: BEST FIT\nName: Maria Santos\nContact: 0917 123 4567";
    $summaryReply = facebookConversationReply($db, $addMessage($allDetails, 'general'), facebookDefaultRules());
    checkFacebook(str_contains($summaryReply, 'PENDING') && str_contains($summaryReply, 'Suggested room:'), 'One customer message produces a clearly labelled suggested-room summary');
    $shortcutDates = $checkIn->modify('+10 days');
    $shortcutEnd = $shortcutDates->modify('+4 days');
    $shortcutReply = facebookConversationReply($db, $addMessage('inquire p ako for ' . $shortcutDates->format('M j') . '-' . $shortcutEnd->format('j'), 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($shortcutReply, 'Dates: ' . $shortcutDates->format('M j')) && str_contains($shortcutReply, 'Total pax: NOT PROVIDED YET') && !str_contains($shortcutReply, 'exactly CONFIRM'), 'Short casual date inquiry revises a confirmation instead of triggering its invalid-answer reminder');
    $shortcutSummary = facebookConversationReply($db, $addMessage('2 pax', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($shortcutSummary, 'PENDING') && str_contains($shortcutSummary, 'Suggested room:'), 'Pax follow-up completes the revised booking review');
    $rateSideReply = facebookConversationReply($db, $addMessage('What are your rates?', 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($rateSideReply, 'rates') && !str_contains($rateSideReply, 'progress is saved') && !str_contains($rateSideReply, 'CONFIRM'), 'Rate side question during confirmation stays informational and omits booking controls');
    $confirmation = $addMessage('CONFIRM', 'general');
    checkFacebook(str_contains(facebookConversationReply($db, $confirmation, facebookDefaultRules()), 'not confirmed'), 'Confirmation creates pending request only');
    $query = $db->prepare("SELECT b.status, e.needs_attention FROM facebook_events e JOIN bookings b ON b.id = e.booking_id WHERE e.id = ?");
    $query->execute([$confirmation['id']]);
    $created = $query->fetch();
    checkFacebook($created && $created['status'] === 'pending' && (int) $created['needs_attention'] === 1, 'Pending booking alerts staff');
    $createdBookingId = (int) $db->query('SELECT MAX(id) FROM bookings')->fetchColumn();
    $bookingCount = (int) $db->query('SELECT COUNT(*) FROM bookings')->fetchColumn();
    $editCheckIn = (new DateTimeImmutable('today', new DateTimeZone('Asia/Manila')))->modify('+240 days');
    $editCheckOut = $editCheckIn->modify('+2 days');
    $newRequest = facebookConversationReply($db, $addMessage($editCheckIn->format('F j') . ' to ' . $editCheckOut->format('j, Y') . ' for 5 guests', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($newRequest, "I'll update your pending request") && str_contains($newRequest, 'PENDING'), 'One message produces a pending-booking update summary');
    $updatedReply = facebookConversationReply($db, $addMessage('confirm', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($updatedReply, 'was updated'), 'Customer confirmation updates the pending request');
    checkFacebook((int) $db->query('SELECT COUNT(*) FROM bookings')->fetchColumn() === $bookingCount, 'Pending update does not create another booking');
    $query = $db->prepare('SELECT check_in, check_out, guests, status FROM bookings WHERE id = ?'); $query->execute([$createdBookingId]);
    $updated = $query->fetch();
    checkFacebook($updated && $updated['check_in'] === $editCheckIn->format('Y-m-d') && $updated['check_out'] === $editCheckOut->format('Y-m-d') && (int) $updated['guests'] === 5 && $updated['status'] === 'pending', 'Pending booking details updated in place');
    $revisedRateDates = $editCheckIn->modify('+30 days');
    $revisedRateEnd = $revisedRateDates->modify('+3 days');
    $partialRateReply = facebookConversationReply($db, $addMessage('Inquire po rates for ' . $revisedRateDates->format('F j') . ' to ' . $revisedRateEnd->format('j'), 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($partialRateReply, 'Dates: ' . $revisedRateDates->format('M j')) && str_contains($partialRateReply, 'Total pax: NOT PROVIDED YET') && str_contains($partialRateReply, 'TOTAL NUMBER OF PAX') && str_contains($partialRateReply, 'Example: 5 pax') && !str_contains($partialRateReply, 'Ilang tao') && str_contains($partialRateReply, 'Name: Maria Santos'), 'Partial rate inquiry clearly asks for the missing pax count');
    $completedRateReply = facebookConversationReply($db, $addMessage('for 5 pax', 'general'), facebookDefaultRules());
    checkFacebook(str_contains($completedRateReply, 'PENDING') && str_contains($completedRateReply, 'Suggested room:') && !str_contains($completedRateReply, 'exactly CONFIRM'), 'Missing guest follow-up produces the revised booking review');

    $rateSender = 'rate-test-' . bin2hex(random_bytes(4));
    $addRateMessage = static function (string $body, string $category) use ($db, $rateSender, $page): array {
        $insert = $db->prepare("INSERT INTO facebook_events (source, page_id, sender_id, kind, guest_name, body, last_customer_message_at, category) VALUES ('facebook', ?, ?, 'message', 'Rate verification', ?, CURRENT_TIMESTAMP, ?)");
        $insert->execute([$page, $rateSender, $body, $category]);
        return ['id' => (int) $db->lastInsertId(), 'page_id' => $page, 'sender_id' => $rateSender, 'body' => $body, 'category' => $category];
    };
    $initialRateReply = facebookConversationReply($db, $addRateMessage('How much are your rooms?', 'rates'), facebookDefaultRules());
    checkFacebook(str_contains($initialRateReply, 'Dates: Needed') && str_contains($initialRateReply, 'Total pax: NOT PROVIDED YET'), 'Rate inquiry asks only for dates and pax');
    $rateReply = facebookConversationReply($db, $addRateMessage($checkIn->format('F j') . ' to ' . $checkOut->format('j, Y') . ' for 5 guests', 'booking'), facebookDefaultRules());
    checkFacebook(str_contains($rateReply, 'PHP') && str_contains($rateReply, 'Want to book?'), 'One rate-details message returns suitable prices');
    $db->rollBack();
    echo "Passed: classification, profile names, reply deduplication, complaint acknowledgement, guided booking state, side questions, pending-only creation and updates, staff alerting, automatic disclosure, automatic queueing, blocked manual delivery, retry policy, and audit persistence. Test rows rolled back.\n";
} catch (Throwable $error) {
    if (isset($db) && $db->inTransaction()) $db->rollBack();
    fwrite(STDERR, 'Facebook verification failed: ' . ($error instanceof PDOException ? 'Database operation failed.' : $error->getMessage()) . "\n");
    exit(1);
}
