import { useCallback, useEffect, useMemo, useState } from 'react';

const statusLabels = { pending: 'New request', confirmed: 'Confirmed', checked_in: 'Checked in', completed: 'Completed', cancelled: 'Cancelled' };

function AdminIcon({ name }) {
  const paths = { calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>, home: <><path d="m3 11 9-8 9 8v10H3Z"/><path d="M9 21v-7h6v7"/></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/></>, logout: <><path d="M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-6"/></>, search: <><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></> };
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function AdminLogin({ onLogin }) {
  const [error,setError] = useState(''); const [loading,setLoading] = useState(false);
  const submit = async event => { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch('/api/admin/login.php',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}); const data = await response.json(); if(!response.ok) throw new Error(data.message || 'Sign in failed.'); onLogin(data.user,data.csrf_token); } catch(exception) { setError(exception.message); } finally { setLoading(false); } };
  return <main className="admin-login"><div className="admin-login__art"><div><span className="admin-wordmark">ODIDEPSE</span><p>Reservations, quietly organized.</p></div></div><section className="admin-login__panel"><div className="admin-login__form"><span className="admin-kicker">Private staff area</span><h1>Welcome back.</h1><p>Sign in to manage guest requests and upcoming stays.</p><form onSubmit={submit}><label>Email address<input type="email" name="email" autoComplete="username" required /></label><label>Password<input type="password" name="password" autoComplete="current-password" required /></label>{error && <p className="admin-error" role="alert">{error}</p>}<button disabled={loading}>{loading ? 'Signing in…' : 'Sign in securely'}</button></form><a href="./">← Return to resort website</a></div></section></main>;
}

function Dashboard({ user, csrfToken, onLogout }) {
  const [bookings,setBookings] = useState([]); const [filter,setFilter] = useState('all'); const [query,setQuery] = useState(''); const [notice,setNotice] = useState('');
  const load = useCallback(async () => { const response = await fetch('/api/admin/bookings.php',{headers:{Accept:'application/json'}}); if(response.status===401) return onLogout(); const data = await response.json(); if(response.ok) setBookings(data.bookings); else setNotice(data.message || 'Could not load bookings.'); },[onLogout]);
  useEffect(() => { load(); },[load]);
  const visible = useMemo(() => bookings.filter(item => (filter==='all'||item.status===filter) && `${item.guest_name} ${item.reference_code} ${item.email}`.toLowerCase().includes(query.toLowerCase())),[bookings,filter,query]);
  const stats = useMemo(() => ({pending:bookings.filter(b=>b.status==='pending').length,confirmed:bookings.filter(b=>b.status==='confirmed').length,guests:bookings.filter(b=>['confirmed','checked_in'].includes(b.status)).reduce((sum,b)=>sum+Number(b.guests),0)}),[bookings]);
  const updateStatus = async (id,status) => { const response = await fetch('/api/admin/bookings.php',{method:'PATCH',headers:{'Content-Type':'application/json',Accept:'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({id:Number(id),status})}); const data = await response.json(); if(!response.ok) return setNotice(data.message || 'Update failed.'); setBookings(current=>current.map(item=>Number(item.id)===Number(id)?{...item,status}:item)); setNotice(`Booking ${data.reference} updated.`); };
  const logout = async () => { await fetch('/api/admin/logout.php',{method:'POST',headers:{'X-CSRF-Token':csrfToken,Accept:'application/json'}}); onLogout(); };
  return <div className="admin-shell"><aside className="admin-sidebar"><span className="admin-wordmark">ODIDEPSE</span><nav><span>Workspace</span><a className="active"><AdminIcon name="calendar"/>Bookings</a><a><AdminIcon name="home"/>Stays</a><a><AdminIcon name="users"/>Guests</a></nav><button onClick={logout}><AdminIcon name="logout"/>Sign out</button></aside><main className="admin-main"><header><div><span className="admin-kicker">Reservations overview</span><h1>Good day, {user.display_name.split(' ')[0]}.</h1></div><div className="admin-avatar">{user.display_name.charAt(0).toUpperCase()}</div></header><section className="admin-stats"><article><span>New requests</span><strong>{stats.pending.toString().padStart(2,'0')}</strong><small>Awaiting your reply</small></article><article><span>Confirmed stays</span><strong>{stats.confirmed.toString().padStart(2,'0')}</strong><small>Upcoming arrivals</small></article><article><span>Expected guests</span><strong>{stats.guests.toString().padStart(2,'0')}</strong><small>Across active stays</small></article></section><section className="booking-board"><div className="booking-board__head"><div><h2>Booking requests</h2><p>{visible.length} {visible.length===1?'reservation':'reservations'}</p></div><label className="admin-search"><AdminIcon name="search"/><input aria-label="Search bookings" placeholder="Search guest or reference" value={query} onChange={e=>setQuery(e.target.value)} /></label></div><div className="filter-row">{['all','pending','confirmed','checked_in','completed','cancelled'].map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value==='all'?'All':statusLabels[value]}</button>)}</div>{notice&&<p className="admin-notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></p>}<div className="booking-table"><div className="booking-row booking-row--head"><span>Guest</span><span>Stay</span><span>Dates</span><span>Status</span></div>{visible.map(booking=><article className="booking-row" key={booking.id}><div><strong>{booking.guest_name}</strong><small>{booking.reference_code} · {booking.guests} guests</small></div><div><strong>{booking.stay_type||'Flexible'}</strong><small>{booking.email}</small></div><div><strong>{booking.check_in}</strong><small>to {booking.check_out}</small></div><select aria-label={`Status for ${booking.guest_name}`} value={booking.status} onChange={e=>updateStatus(booking.id,e.target.value)}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></article>)}{visible.length===0&&<div className="empty-state"><AdminIcon name="calendar"/><h3>No reservations here yet.</h3><p>New booking requests will appear automatically.</p></div>}</div></section></main></div>;
}

export default function AdminApp() {
  const [session,setSession] = useState({loading:true,user:null,csrfToken:''});
  const check = useCallback(async () => { try { const response=await fetch('/api/admin/session.php',{headers:{Accept:'application/json'}}); const data=await response.json(); setSession(response.ok?{loading:false,user:data.user,csrfToken:data.csrf_token}:{loading:false,user:null,csrfToken:''}); } catch { setSession({loading:false,user:null,csrfToken:''}); } },[]);
  useEffect(()=>{check();},[check]);
  if(session.loading) return <div className="admin-loading"><span>ODIDEPSE</span></div>;
  if(!session.user) return <AdminLogin onLogin={(user,csrfToken)=>setSession({loading:false,user,csrfToken})}/>;
  return <Dashboard user={session.user} csrfToken={session.csrfToken} onLogout={()=>setSession({loading:false,user:null,csrfToken:''})}/>;
}
